### ISSUE TITLE
Highlighting where a competency has associated learning resources

### ISSUE THREAD

**Issue by stuartasutton** [ld4pe/learning-resources#3]
When a user accesses learning resources by first browsing the competency index, it would be useful if there were a way in the index listing to signal to the user those index nodes that actually have mapped resources. In the wild, that kind of signaling happens in different ways. Sometimes there is an icon with nodes that have resources. Other times there may be an indication of the number or attached resources. And other times nodes with resources may be a different color than those nodes without resources. I have also seen a very bad way of doing it and that is to not show index nodes with no resources. I say "bad" because an index tree truncated to entries with attached learning resources is disorienting in terms of grounding the user in the overall context.

The goal would be to avoid frustrating users who click on index links and find no related resources. IMHO any signaling mechanism--icon, color, count--works.

**Comment by davidwtalley** [comment]
I agree that this is an important priority. A count of associated resources in parens following the competency name would be a pretty standard way of implementing something like this. I prefer that approach to placing an icon, whose meaning may be difficult to convey to an unfamiliar user, or a color change, which may not be visible to users with varying levels of color perception. Also, the counts on a list of competencies would convey information about the relative levels of representation within the learning resource collection.
